version: '3'
services:
  db:
    image: postgres:9.5.7
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=db
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DATABASE_HOST='db'
      - DATABASE_USERNAME='postgresql'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
