default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mortgage_development

test:
  <<: *default
  database: mortgage_test

production:
  <<: *default
  database: mortgage_production
  username: mortgage
  password: <%= ENV['MORTGAGE_DATABASE_PASSWORD'] %>
