default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: it_glue_development

test:
  <<: *default
  database: it_glue_test

production:
  <<: *default
  database: it_glue_production
  username: it_glue
  password: <%= ENV['IT_GLUE_DATABASE_PASSWORD'] %>
